# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AoiTranslateUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from os import error
from PyQt5 import QtCore, QtGui, QtWidgets
from google_trans_new.constant import LANGUAGES
import AoiTranslateFuntion 
import pyperclip
import time 
import threading


# clipboardData = "clipboardData Mặc định"

lang_input = "ja"
lang_output = "vi"
translators = ["google_trans_new", "googletrans"]
LANGUAGES_ID = AoiTranslateFuntion.LANGUAGES_ID

# print(LANGUAGES_ID)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(671, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxTranslator = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxTranslator.setGeometry(QtCore.QRect(150, 4, 511, 22))
        self.comboBoxTranslator.setObjectName("comboBoxTranslator")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 194, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 64, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBoxSourceLanguage = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxSourceLanguage.setGeometry(QtCore.QRect(150, 40, 191, 22))
        self.comboBoxSourceLanguage.setObjectName("comboBoxSourceLanguage")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 40, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBoxTranslatedLanguage = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxTranslatedLanguage.setGeometry(QtCore.QRect(450, 40, 211, 22))
        self.comboBoxTranslatedLanguage.setObjectName("comboBoxTranslatedLanguage")
        self.textEdit_SourceText = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_SourceText.setGeometry(QtCore.QRect(10, 84, 651, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.textEdit_SourceText.setFont(font)
        self.textEdit_SourceText.setObjectName("textEdit_SourceText")
        self.textEdit_TranslatedText = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_TranslatedText.setGeometry(QtCore.QRect(10, 214, 651, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.textEdit_TranslatedText.setFont(font)
        self.textEdit_TranslatedText.setObjectName("textEdit_TranslatedText")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 2, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 671, 21))
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.actionApp_by_https_vatthatlactubautroi_blogspot_com = QtWidgets.QAction(MainWindow)
        self.actionApp_by_https_vatthatlactubautroi_blogspot_com.setObjectName("actionApp_by_https_vatthatlactubautroi_blogspot_com")
        self.menuSetting.addAction(self.actionApp_by_https_vatthatlactubautroi_blogspot_com)
        self.menubar.addAction(self.menuSetting.menuAction())
        # comboBox Add Items ===================================================================================================================
        self.comboBoxTranslator.addItems(translators)
        for i in LANGUAGES:
            self.comboBoxSourceLanguage.addItem(LANGUAGES.get(i))
            self.comboBoxTranslatedLanguage.addItem(LANGUAGES.get(i))
        self.comboBoxSourceLanguage.setCurrentText("japanese")
        self.comboBoxTranslatedLanguage.setCurrentText("vietnamese")
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # EVENT =================================================================================================================================
        self.comboBoxTranslator.currentIndexChanged.connect(self.comboBoxTranslator_changed)
        self.comboBoxSourceLanguage.currentIndexChanged.connect(self.input_changed)
        self.comboBoxTranslatedLanguage.currentIndexChanged.connect(self.output_changed)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AoiTranslate"))
        self.label.setText(_translate("MainWindow", "Translated :"))
        self.label_2.setText(_translate("MainWindow", "Source Text:"))
        self.label_3.setText(_translate("MainWindow", "Source language:"))
        self.label_4.setText(_translate("MainWindow", "Translate to:"))
        
        self.textEdit_SourceText.setPlainText("HI................")
        # self.textEdit_SourceText.setHtml(_translate("MainWindow", "_"))
        # self.textEdit_TranslatedText.setHtml(_translate("MainWindow", "_"))
        self.label_6.setText(_translate("MainWindow", "Select translator"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.actionApp_by_https_vatthatlactubautroi_blogspot_com.setText(_translate("MainWindow", "App by Aoi - https://vatthatlactubautroi.blogspot.com"))

    # FUNCTION ==============================================================================================================================================
    def comboBoxTranslator_changed(self):
        print("Translator changed: ", str(self.comboBoxTranslator.currentText()))
    def input_changed(self):
        lang_id = self.comboBoxSourceLanguage.currentIndex()
        lang_input = LANGUAGES_ID.get(lang_id)
        print('lang_input changed: ', lang_id, "-", lang_input,"-", LANGUAGES.get(lang_input))
    def output_changed(self):
        lang_id = self.comboBoxTranslatedLanguage.currentIndex()
        lang_output = LANGUAGES_ID.get(lang_id)
        print('lang_output changed: ', lang_id, "-",lang_output,"-", LANGUAGES.get(lang_output))

    # Set text on TextEdit
    def textEdit_SourceText_Set(self, text):
        self.textEdit_SourceText.setPlainText(text)
    def textEdit_TranslatedText_Set(self, text):
        self.textEdit_TranslatedText.setPlainText(text)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    print("=============ok?")
    
    
    # clipboardData = ""
    # Aoi Translate
    def translate_threading(clipboardData = "hello"):
        print(clipboardData)
        while 1 == 1:
            newcbData = pyperclip.paste()
            if newcbData != clipboardData:
                clipboardData = newcbData
                ui.textEdit_SourceText_Set(clipboardData)
                print(lang_input, "=>", lang_output, "=====================================================================================================")
                translated_text = AoiTranslateFuntion.translating(clipboardData, lang_input, lang_output)
                print(translated_text)
            else:
                time.sleep(0.5)

    translate_run = threading.Thread(name="translate_threading", target=translate_threading)
    # translate_run.setDaemon(True)
    
    try:
        translate_run.start()
    except:
        print(error)
    print("threading : ",threading.activeCount())

    sys.exit(app.exec_())
